force-app/main/default/objects/User_Leaves__c/User_Leaves__c.object-meta.xml
<CustomObject>
    <label>User Leaves</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Leaves</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Leaves__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <label>Leave Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned Leave</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Unpaid Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Leaves__c/fields/Remaining_Leaves__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Leaves__c</fullName>
    <formula>Total_Allocated__c  -  Total_Consumed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Leaves__c/fields/Total_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Total_Allocated__c</fullName>
    <label>Total Allocated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Leaves__c/fields/Total_Consumed__c.field-meta.xml
<CustomField>
    <fullName>Total_Consumed__c</fullName>
    <label>Total Consumed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Leaves__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Leaves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/leaveManagementSys_UserLeaveVal_lwc.cls
public class leaveManagementSys_UserLeaveVal_lwc {
	@AuraEnabled(cacheable=true)
    public static List<User_Leaves__c> userLeavesData(String strUSERID) {
        system.debug('Leave Apex code in action '+ strUSERID);
        List<User_Leaves__c> userLeaves = [SELECT ID,User__c,Total_Allocated__c,Total_Consumed__c,Remaining_Leaves__c,Leave_Type__c FROM User_Leaves__c WHERE User__c =: strUSERID];
        System.debug(userLeaves);
        return userLeaves;
    }
}