force-app/main/default/objects/User_Leaves__c/User_Leaves__c.object-meta.xml
<CustomObject>
    <label>User Leaves</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Leaves</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Leaves__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Leaves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/leaveManagementSys_UserLeaveVal_test.cls
@isTest
public class leaveManagementSys_UserLeaveVal_test {
	@testSetup
    static void createRecords() {
        //can create new user with profile & all
    }
    @isTest
    static void testingCode(){
        String UserID = userInfo.getUserId();
        List<User_Leaves__c> leaveData = leaveManagementSys_UserLeaveVal_lwc.userLeavesData(UserID);
        //User_Leaves__c random_UserID = [SELECT Id,User__c FROM User_Leaves__c LIMIT 1];
        //List<User_Leaves__c> leaveData = leaveManagementSys_UserLeaveVal_lwc.userLeavesData(random_UserID.User__c);
    }
}