force-app/main/default/objects/Leave_Requests__c/Leave_Requests__c.object-meta.xml
<CustomObject>
    <label>Leave Requests</label>
    <nameField>
        <displayFormat>LR-{0000}</displayFormat>
        <label>Leave Requests Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Requests__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned Leave</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Unpaid Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Requests__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approve</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Requests__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leave_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/leaveManagementSys_ApproveVal_test.cls
@isTest
public class leaveManagementSys_ApproveVal_test {
    @TestSetup
    static void createRecord(){
        String UserID = userInfo.getUserId();
        List<Leave_Requests__c> newLeaves = new List<Leave_Requests__c>();
        for(Integer i=0;i<6;i++){
            Leave_Requests__c lreq = new Leave_Requests__c();
            lreq.From_Date__c = system.today();
            lreq.To_Date__c = system.today().addDays(1);
            if(i<2){
                lreq.Leave_Type__c = 'Planned Leave';
            }else if(i<4){
                lreq.Leave_Type__c = 'Sick Leave';
            }else if(i<6){
                lreq.Leave_Type__c = 'Unpaid Leave';
            }
            lreq.User__c = UserID;
            lreq.Reason__c = 'testing';
            newLeaves.add(lreq);
        }
        Insert newLeaves;
    }
    @isTest
    static void testingCode(){
		List<Leave_Requests__c> newLevList = [SELECT ID, User__c, Reason__c, Status__c FROM Leave_Requests__c WHERE Reason__c ='testing'];
        for(Leave_Requests__c LRlist:newLevList){
            LRlist.Status__c = 'Approve';
        }
        Update newLevList;
    }
}