force-app/main/default/objects/Leave_Requests__c/Leave_Requests__c.object-meta.xml
<CustomObject>
    <label>Leave Requests</label>
    <nameField>
        <displayFormat>LR-{0000}</displayFormat>
        <label>Leave Requests Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Requests__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned Leave</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Unpaid Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Requests__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approve</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Requests__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leave_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/leaveManagementSys_UserDataRtn_lwc.cls
public class leaveManagementSys_UserDataRtn_lwc {
	@AuraEnabled(cacheable=true)
    public static List<Leave_Requests__c> userToData(String strRequire) {
        //System.debug('Employee Leave Record as per USER'+ [SELECT Name,Leave_Type__c,From_Date__c,To_Date__c,Reason__c,Status__c,Manager_Comment__c,User__c,OwnerId FROM Leave_Requests__c WHERE OwnerId=:UserInfo.getUserID() with SECURITY_ENFORCED]);
        //System.debug('Employee Leave Record full search'+ [SELECT Name,Leave_Type__c,From_Date__c,To_Date__c,Reason__c,Status__c,Manager_Comment__c,User__c,OwnerId FROM Leave_Requests__c]);

        LIST<Leave_Requests__c> returnData = new LIST<Leave_Requests__c>();
        if(strRequire == 'onlyPersonalData'){
            System.debug('In Only Personal Data');
            return [SELECT Name,Leave_Type__c,From_Date__c,To_Date__c,Reason__c,Status__c,Manager_Comment__c,User__c,OwnerId FROM Leave_Requests__c WHERE OwnerId=:UserInfo.getUserID() with SECURITY_ENFORCED];
        }else if(strRequire == 'allData'){
            System.debug('In All Data');
            return [SELECT Name,Leave_Type__c,From_Date__c,To_Date__c,Reason__c,Status__c,Manager_Comment__c,User__c,OwnerId FROM Leave_Requests__c];
        }
        return returnData;
    }
}